services:
  - type: web
    name: xio-payplus
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app.mini_app:create_app()" --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        value: xiolis_bot
      - key: ADMIN_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MINI_APP_URL
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromGroup:
          name: xio-payplus
          type: WEB_SERVICE
          property: hostname
    healthCheckPath: /health
