services:
  - type: web
    name: xio-payplus
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app.mini_app:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: MINI_APP_URL
        fromService:
          type: web
          name: xio-payplus
          property: url
